server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          #default-label: config-service
          default-label: eureka
          uri: https://github.com/carmagedon07/SpringCloudPractice3
          search-paths: config-data

  application:
    name: config-service

